[workflow]
dataset = 'prophecy'
input_datasets = ['prophecy']
dataset_gcp_project = 'prophecy-339301'
sequencing_type = 'genome'

access_level = 'full'

skip_samples = [
  'CPG216275',  # https://batch.hail.populationgenomics.org.au/batches/74382
  'CPG216010',  # https://batch.hail.populationgenomics.org.au/batches/74382
  'CPG214858',  # missing GVCF
  'CPG216481',  # missing GVCF
]

scatter_count = 20
output_version = '0.1'
vds_version = '0.1'

[hail]
billing_project = 'prophecy'
