[workflow]
dataset = 'prophecy'
datasets = ['prophecy']
access_level = 'test'
only_batches = [1, 2]
dataset_gcp_project = 'prophecy-339301'
check_inputs = false
check_expected_outputs = true
skip_samples_with_missing_input = true
sequencing_type = 'genome'
skip_samples = [
  'CPG216275',  # https://batch.hail.populationgenomics.org.au/batches/74382
  'CPG216010',  # https://batch.hail.populationgenomics.org.au/batches/74382
  'CPG214858',  # missing GVCF
  'CPG216481',  # missing GVCF
]
scatter_count = 20
output_version = '0.1'
vds_version = '0.1'

[hail]
billing_project = 'prophecy'
query_backend = 'spark'
local = true

[combiner]
intervals = 'gs://cpg-reference/hg38/v0/test/exome_calling_regions.v1.chr21.interval_list'
use_exome_default_intervals = true
