[workflow]
access_level = 'test'
check_inputs = false
check_expected_outputs = true
skip_samples_with_missing_input = true
scatter_count = 20
output_version = '0.1'
vds_version = '0.1'

[hail]
query_backend = 'spark'
local = true
