name: Test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install
        run: |
          pip install -r requirements-dev.txt
          pip install .

      - name: Test import
        run: python -c "import larcoh.utils"

      - name: Run unit tests
        run: python -m pytest test/test.py
